### ISSUE TITLE
Add "What's Next for DevOps"

### ISSUE THREAD

**Issue by justisGipson** [hellerve/programming-talks#104]
Emily Freeman's FailoverConf talk - "What's next for Devops" would be a great addition – I think.

https://www.youtube.com/watch?v=_Zydz0__KA8

Thoughts?

**Comment by hellerve** [comment]
Hey! Thank you for contributing <3

I’m currently on parental leave and am mostly focused on taking care of my child, trying not to spend too much time in front of my computer. I’ll try and watch that talk when I find the time and mental space, but it’ll probably be until next month.

See you then!

**Comment by justisGipson** [comment]
Sounds good! Enjoy your time away!
