### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by dcmoore** [hellerve/programming-talks#107]
[Reactive Programming Overview](https://www.youtube.com/watch?v=dwP1TNXE6fc) [00:09:18] by Jafar Husain (very concise and dense) (2014)

The link for the above talk is dead. Is there another place it is hosted?

**Comment by hellerve** [comment]
The Git history says I added this talk in 633694d in 2015. Sadly I can’t remember much about it, so I’d consider the link dead and remove it for now. :(

**Comment by bodiam** [comment]
Hi, wouldn't this be the same link? (It has the same length too)

https://www.youtube.com/watch?v=-8Y1-lE6NSA

**Comment by hellerve** [comment]
The description does say that this is a mirror of the original. Looking at it again, it’s more of an interview than a talk, though, so I think leaving it out might actually be the right call!
