### ISSUE TITLE
OPLSS Talks

### ISSUE THREAD

**Issue by m1dnight** [hellerve/programming-talks#17]
I am making this an issue because I am not sure if it fits the format.

The Oregon Programming Languages Summer School is a known summer school about programming language design, especially it's theoretical underpinnings.

The talks are all online:
https://www.cs.uoregon.edu/research/summerschool/summer16/curriculum.php
https://www.cs.uoregon.edu/research/summerschool/summer15/curriculum.html
https://www.cs.uoregon.edu/research/summerschool/summer14/curriculum.html
https://www.cs.uoregon.edu/research/summerschool/summer13/curriculum.html

Etc..

**Comment by hellerve** [comment]
Hey, thanks for your contribution!

While I do think those talks are helpful for leaners, I do not really think I should include them in this list. I know of a few good resources for lectures online I think the list will get even larger and more unmanageable than it already is if we add those lectures. Is that reasonable?

That said, you could just carbon-copy the layout of the list and make one of your own if you'd like!
