### ISSUE TITLE
Date on videos

### ISSUE THREAD

**Issue by pixelgrid** [hellerve/programming-talks#19]
I could go through the videos and get the date for each of them.
It usually helps to know how old a video/topic discussed is.

The addition of new links should have a requirement of having the date in the title

**Comment by hellerve** [comment]
Sounds like a good idea. Do you have a suggestion for the new format, i.e. where we place the date?

**Comment by pixelgrid** [comment]
it can go in the brackets before the total time

Advanced C Coding For Fun! [2011, 00:46:53] by Rusty Russell

Another format with more info about each talk could be the following using emoticons

Advanced C Coding For Fun! 📍Linux.conf.au 📅 2011 ⏲ 00:46:53 👤 Rusty Russell

**Comment by hellerve** [comment]
I'm not a big fan of emoticons myself but I guess many people are and it makes the whole format a bit more concise.

I personally would still tend towards the first format, though. Maybe I'm just an old fart (I'm not even halfway through my twenties, goshdarnit).

**Comment by hellerve** [comment]
Closing this as it seems like a relatively abandoned issue and does not seem to have gained much traction to begin with.
