### ISSUE TITLE
Denotational Design

### ISSUE THREAD

**Issue by comraq** [hellerve/programming-talks#23]
I suggest including the following three videos:

Lambda Jam 2015 - Conal Elliott - The Essence and Origins of Functional Reactive Programming
https://www.youtube.com/watch?v=j3Q32brCUAI

Lambda Jam 2015 - Conal Elliott - A More Elegant Specification for FRP
https://www.youtube.com/watch?v=teRC_Lf61Gw

Lambda Jam 2015 - Conal Elliott - Denotational Design: From Meanings To Programs
https://www.youtube.com/watch?v=bmKYiUOEo2A

The reason being, Conal mentions how "functional" programming is very ill defined and the essence of fp may be better understood as denotative.

**Comment by hellerve** [comment]
Sounds interesting, I will go through them and add them when I am and don't have any objection (I normally don't).

**Comment by hellerve** [comment]
I added all of the talks. Thank you for showing me, they are really deeply insightful.

**Comment by comraq** [comment]
Glad you found these insightful, as it gave me a better understanding of what "functional" programming is really about.
