### ISSUE TITLE
Adding years to the list

### ISSUE THREAD

**Issue by dospunk** [hellerve/programming-talks#31]
Adding the year of the talk to the list would be helpful

**Comment by hellerve** [comment]
This was discussed before in #19. I'm generally in favor of that, I just don't currently have the time to go through the videos.

**Comment by dospunk** [comment]
I'm working on it now

**Comment by hellerve** [comment]
Thanks a lot, I really appreciate that!

**Comment by martpie** [comment]
@dospunk Do you need help? ;)

**Comment by hellerve** [comment]
@KeitIG if you want to take this over, feel free. This issue somehow just fizzled out.

**Comment by dospunk** [comment]
Oh wow I completely forgot about this whoops, [here is my fork ](https://github.com/dospunk/programming-talks) if anyone wants to contribute to it.
