### ISSUE TITLE
Under which section should this talk go?

### ISSUE THREAD

**Issue by catb0t** [hellerve/programming-talks#38]
I'm really enjoying (and still watching...) Breaking The x86 Instruction Set by Christoper Domas (https://www.youtube.com/watch?v=KrksBdWcZgQ). It was presented at Black Hat USA 2017, and it's 44:28 long.

It's about hacking and messing with Intel's 8086 instruction set architecture (ISA) so it goes under **hardware**, but it's also about security, **debugging**, **system architecture**, etc.

Which section do you think fits it best?

**Comment by hellerve** [comment]
That’s a good question (and a good talk). I usually look at the conference it was presented at when in doubt. In this case I would then file it under Security.

**Comment by catb0t** [comment]
We don't have a security section -- shall we make one?

**Comment by hellerve** [comment]
Sounds good to me!

**Comment by hellerve** [comment]
Is it alright with you if I add this now? This issue seems to have slipped my mind—sorry.

**Comment by catb0t** [comment]
whoops, i need to check GH notifs more often. yes, it sounds good to me!

**Comment by hellerve** [comment]
Thanks!
