### ISSUE TITLE
404 - The Website Obesity Crisis [00:53:10] by Maciej Ceglowski

### ISSUE THREAD

**Issue by shoooe** [hellerve/programming-talks#47]
The link in "The Website Obesity Crisis [00:53:10] by Maciej Ceglowski" yields a 404-like page.

**Comment by catb0t** [comment]
The video is made private and embed-only, so now the link is https://www.webdirections.org/blog/the-website-obesity-crisis/

**Comment by hellerve** [comment]
That’s annoying. Okay, I usually am a bit hesitant to link to blog posts with embedded videos, but I guess there is no other way.

**Comment by hellerve** [comment]
Would a disclaimer on the list be overkill or prudent? I’m not sure whether I’m unjustly defensive about putting embedded videos on this list.

**Comment by catb0t** [comment]
I don't think a disclaimer on the list would be a bad idea, but is it a better idea than just re-uploading that video to YouTube? 

I'll do that right now (with a link to the original blog post, of course)

**Comment by catb0t** [comment]
ok, here's the mirror link, it depends if you want it or not https://www.youtube.com/watch?v=iYpl0QVCr6U

**Comment by hellerve** [comment]
Thank you, I feel better about that!

@catb0t, thanks for your work!
