### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kholbekj** [hellerve/programming-talks#5]
Hey, awesome list, can I shamelessly steal it's contents? Working on an app for rating/labeling/previewing talks, this would be a nice seed.

**Comment by hellerve** [comment]
Of course! That thing is in the public domain, use it as you like.

**Comment by kholbekj** [comment]
Neat, consider it done >:D

**Comment by jletellier** [comment]
Also consider the [Beerware license](https://en.wikipedia.org/wiki/Beerware) in case you meet one of the contributors :)

**Comment by hellerve** [comment]
That is probably a good idea. :+1:

I'll buy you a beer next time we meet,@jletellier. Promise.

**Comment by kholbekj** [comment]
That makes perfect sense! In case you're interested, the project is (in an early phase) here:
https://github.com/kholbekj/codetalks

**Comment by hellerve** [comment]
Phoenix. Pretty. Wanted to use that at some point. The website doesn't seem to work currently, though.

I'll be sure to check regularly, as I'm really interested.

**Comment by kholbekj** [comment]
It does technically work if you visit /auth first :)
And yes, they released 1.0, seemed sane point to try it for real.
(only one example talk at /talks), but hey.
