### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by pepasflo** [hellerve/programming-talks#64]
Not actually an issue, I just wanted to say I am so happy to check in on this list ~6 months later and find that it is still being updated!  What an incredible resource!

**Comment by hellerve** [comment]
Thank you! Feedback like this means a lot; it’s great to hear that what started as a little list of talks I watched and enjoyed actually helps people!

As for your other issue (#65) and PR (#66), I will get to them soon. I have a few talks on my todo list right now, but it shouldn’t take longer than, say, a week.

**Comment by hellerve** [comment]
Is it alright if I close this issue?

**Comment by pepasflo** [comment]
Yup :)
