### ISSUE TITLE
Durations on links

### ISSUE THREAD

**Issue by StefanMich** [hellerve/programming-talks#7]
It would be nice to have the durations of the videos right beside the link

**Comment by Thalmann** [comment]
+1

**Comment by hellerve** [comment]
That is a good suggestion, thanks! I will add that to every new video, but it will likely be some time until I get around to add it to the videos that are already on the list.

**Comment by Thalmann** [comment]
I am currently writing a python script which will add the durations of the videos in the README.md file.
I will add a PR later.

**Comment by hellerve** [comment]
How very nice of you. Thanks.
