### ISSUE TITLE
Dead links: Dependently typed functional programming in Idris 

### ISSUE THREAD

**Issue by catb0t** [hellerve/programming-talks#71]
Here are the exercises / slides from David Christiansen but the same links are dead links.  https://github.com/david-christiansen/IdrisAtGalois2015

I think Galois' entire Vimeo channel was removed or made private, as it seems to no longer exist (or has only 5 videos on it, compared to dozens of talks they've hosted).

It's very unfortunate and I wish I could keep a copy of all the videos on the list, but I haven't got the disk space. 

We could replace it with (mirrored) versions of Edwin Brady's 3 lectures on the same topic with a similar title, https://vimeo.com/61576198 (although I do like Christiansen) 

They are uploaded on his account and listed on the Idris website, https://www.idris-lang.org/dependently-typed-functional-programming-with-idris-course-videos-and-slides/ 

So maybe they are less susceptible to disappearing. 

Any ideas?

**Comment by catb0t** [comment]
Edwin Brady's lectures are introduced by David Christiansen. That's quite funny.

**Comment by hellerve** [comment]
Good catch! I’m going through Edwin Brady’s lectures at the moment (I have some time on the train today), but I’m not sure I will get through them soon. Idris is not the simplest topic for me to get through quickly, in all honesty.

**Comment by hellerve** [comment]
So, I watched the entire set of talks now and enjoyed them. I do think I liked Christiansen’s more, but oh well! You found a great substitute!

You said in an earlier comment that there were three talks in this series; I count four. Was that a typo or were you not aware of the fourth?

**Comment by catb0t** [comment]
It was a typo, because I was thinking about Christiansen's talks.

**Comment by hellerve** [comment]
Perfect! Should I add those talks or do you want to?

**Comment by catb0t** [comment]
I can add them!
