### ISSUE TITLE
Two talk suggestions

### ISSUE THREAD

**Issue by aos** [hellerve/programming-talks#90]
Hello again @hellerve ! I hope I haven't been trolling your repos too much lately :-) Here are two talks I've watched recently that I really enjoyed, and I think you would appreciate:

1. [Performance Matters](https://www.youtube.com/watch?v=r-TLSBdHe1A) [00:42:14] by **Emery Berger** (2019)
    - This talk was from this year's Strangeloop and was about how our current approach to performance optimizations don't mean much. Not sure how to categorize this one, maybe under _Performance Engineering_?
2. [On the Expressive Power of Programming Languages](https://www.youtube.com/watch?v=43XaZEn2aLc) [00:59:03] by **Shriram Krishnamurthi** (2019)
    - This talk was from this year's PWLConf and was about how we can formalize programming language "expressiveness". The speaker is very engaging! Probably categorize this under _Programming Language Theory_.

**Comment by hellerve** [comment]
Hey!

Of course I don’t mind you stopping by, and your input is super appreciated!

I’m just finishing up “Performance Matters” as I type this, and I’d definitely like to add this to the list. Should I go ahead and add it myself, or do you want to submit a PR? Your classifications make sense to me.

Cheers

**Comment by aos** [comment]
You can go ahead and add them yourself -- I think you can just copy-paste the raw markdown from my post as I tried to use your formatting :-)

**Comment by hellerve** [comment]
Thanks! Those were both very fun and illuminating!
